import React from 'react'
import { View, Text } from '@tarojs/components'

// 图标映射表 - 将 Lucide React 图标转换为 Unicode 符号
const iconMap = {
  BookOpen: '📖',
  User: '👤', 
  Target: '🎯',
  ChevronUp: '▲',
  ChevronDown: '▼',
  Book: '📚',
  Filter: '🔍',
  RotateCcw: '🔄',
  Play: '▶️',
  Stop: '⏹️',
  ChevronRight: '▶',
  ChevronLeft: '◀',
  Home: '🏠',
  Settings: '⚙️',
  Search: '🔍',
  Plus: '➕',
  Minus: '➖',
  Check: '✓',
  X: '✗',
  Star: '⭐',
  Heart: '❤️',
  MessageCircle: '💬',
  Phone: '📞',
  Mail: '📧',
  Calendar: '📅',
  Clock: '🕐',
  MapPin: '📍',
  Download: '⬇️',
  Upload: '⬆️',
  Share: '📤',
  Copy: '📋',
  Edit: '✏️',
  Trash: '🗑️',
  Eye: '👁️',
  EyeOff: '👁️‍🗨️',
  Lock: '🔒',
  Unlock: '🔓',
  Bell: '🔔',
  BellOff: '🔕',
  Camera: '📷',
  Image: '🖼️',
  File: '📄',
  Folder: '📁',
  FolderOpen: '📂',
  Archive: '📦',
  Tag: '🏷️',
  Link: '🔗',
  ExternalLink: '🔗',
  RefreshCw: '🔄',
  RotateCw: '🔄',
  Maximize: '⛶',
  Minimize: '⛷️',
  Volume2: '🔊',
  VolumeX: '🔇',
  Mic: '🎤',
  MicOff: '🎤',
  Video: '📹',
  VideoOff: '📹',
  Headphones: '🎧',
  Speaker: '🔊',
  Wifi: '📶',
  WifiOff: '📶',
  Battery: '🔋',
  BatteryLow: '🔋',
  Zap: '⚡',
  Sun: '☀️',
  Moon: '🌙',
  Cloud: '☁️',
  CloudRain: '🌧️',
  CloudSnow: '❄️',
  Wind: '💨',
  Thermometer: '🌡️',
  Droplets: '💧',
  Flame: '🔥',
  Snowflake: '❄️',
  Umbrella: '☂️',
  Rainbow: '🌈',
  Globe: '🌍',
  Compass: '🧭',
  Map: '🗺️',
  Navigation: '🧭',
  Flag: '🚩',
  Award: '🏆',
  Trophy: '🏆',
  Medal: '🏅',
  Crown: '👑',
  Gift: '🎁',
  PartyPopper: '🎉',
  Confetti: '🎊',
  Cake: '🎂',
  Coffee: '☕',
  Pizza: '🍕',
  Apple: '🍎',
  Banana: '🍌',
  Carrot: '🥕',
  Leaf: '🍃',
  Tree: '🌳',
  Flower: '🌸',
  Bug: '🐛',
  Bird: '🐦',
  Cat: '🐱',
  Dog: '🐶',
  Fish: '🐟',
  Whale: '🐋',
  Butterfly: '🦋',
  Bee: '🐝',
  Spider: '🕷️',
  Ant: '🐜',
  Ladybug: '🐞',
  Snail: '🐌',
  Frog: '🐸',
  Turtle: '🐢',
  Lizard: '🦎',
  Snake: '🐍',
  Dragon: '🐉',
  Unicorn: '🦄',
  Horse: '🐴',
  Cow: '🐄',
  Pig: '🐷',
  Sheep: '🐑',
  Goat: '🐐',
  Rabbit: '🐰',
  Hamster: '🐹',
  Mouse: '🐭',
  Rat: '🐀',
  Squirrel: '🐿️',
  Hedgehog: '🦔',
  Bat: '🦇',
  Bear: '🐻',
  Panda: '🐼',
  Koala: '🐨',
  Monkey: '🐵',
  Gorilla: '🦍',
  Orangutan: '🦧',
  Elephant: '🐘',
  Rhinoceros: '🦏',
  Hippopotamus: '🦛',
  Giraffe: '🦒',
  Zebra: '🦓',
  Deer: '🦌',
  Moose: '🫎',
  Camel: '🐪',
  DromedaryCamel: '🐫',
  Llama: '🦙',
  Kangaroo: '🦘',
  Sloth: '🦥',
  Otter: '🦦',
  Skunk: '🦨',
  Raccoon: '🦝',
  Badger: '🦡',
  Beaver: '🦫',
  Seal: '🦭',
  Walrus: '🦭',
  PolarBear: '🐻‍❄️',
  Penguin: '🐧',
  Duck: '🦆',
  Goose: '🪿',
  Swan: '🦢',
  Turkey: '🦃',
  Chicken: '🐔',
  Rooster: '🐓',
  Hen: '🐔',
  Chick: '🐤',
  BabyChick: '🐥',
  HatchingChick: '🐣',
  FrontFacingBabyChick: '🐥',
  Eagle: '🦅',
  Owl: '🦉',
  Parrot: '🦜',
  Peacock: '🦚',
  Flamingo: '🦩',
  Dove: '🕊️',
  Sparrow: '🐦',
  Hummingbird: '🦜',
  Toucan: '🦜',
  Woodpecker: '🦜',
  Pelican: '🦜',
  Stork: '🦜',
  Crane: '🦜',
  Heron: '🦜',
  Ibis: '🦜',
  Spoonbill: '🦜',
  Cormorant: '🦜',
  Gannet: '🦜',
  Booby: '🦜',
  Frigatebird: '🦜',
  Albatross: '🦜',
  Petrel: '🦜',
  Shearwater: '🦜',
  StormPetrel: '🦜',
  DivingPetrel: '🦜',
  Grebe: '🦜',
  Loon: '🦜',
  Auk: '🦜',
  Puffin: '🦜',
  Guillemot: '🦜',
  Razorbill: '🦜',
  Murre: '🦜',
  Kittiwake: '🦜',
  Gull: '🦜',
  Tern: '🦜',
  Skimmer: '🦜',
  Jaeger: '🦜',
  Skua: '🦜',
  Goshawk: '🦜',
  Sparrowhawk: '🦜',
  Buzzard: '🦜',
  Harrier: '🦜',
  Kite: '🦜',
  Osprey: '🦜',
  Vulture: '🦜',
  Condor: '🦜',
  SecretaryBird: '🦜',
  Seriema: '🦜',
  Cariama: '🦜',
  Bustard: '🦜'
}

interface IconProps {
  name: keyof typeof iconMap
  size?: number
  className?: string
  color?: string
}

export const Icon: React.FC<IconProps> = ({ 
  name, 
  size = 24, 
  className = '', 
  color = 'currentColor' 
}) => {
  const iconSymbol = iconMap[name] || '?'
  
  return (
    <Text 
      className={`icon ${className}`}
      style={{
        fontSize: `${size}px`,
        color: color,
        display: 'inline-block',
        lineHeight: 1
      }}
    >
      {iconSymbol}
    </Text>
  )
}

export default Icon
